const taskTypes = {
   FETCH_TASK: 'FETCH_TASK',
   FETCH_TASK_SUCCESS: 'FETCH_TASK_SUCCESS',
   FETCH_TASK_FAIL: 'FETCH_TASK_FAIL',

   SEARCH_TASK: 'SEARCH_TASK',
   SEARCH_TASK_SUCCESS: 'SEARCH_TASK_SUCCESS',

   ADD_TASK: 'ADD_TASK',
   ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
   ADD_TASK_FAIL: 'ADD_TASK_FAIL',

   SET_TASK_EDITING: 'SET_TASK_EDITING',

   UPDATE_TASK: 'UPDATE_TASK',
   UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
   UPDATE_TASK_FAIL: 'UPDATE_TASK_FAIL',

   DELETE_TASK: 'DELETE_TASK',
   DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
   DELETE_TASK_FAIL: 'DELETE_TASK_FAIL'
}

export default taskTypes
