const taskTypes = {
   FETCH_TASK: 'FETCH_TASK',
   FETCH_TASK_SUCCESS: 'FETCH_TASK_SUCCESS',
   FETCH_TASK_FAIL: 'FETCH_TASK_FAIL',

   SEARCH_TASK: 'SEARCH_TASK',
   SEARCH_TASK_SUCCESS: 'SEARCH_TASK_SUCCESS',

   ADD_TASK: 'ADD_TASK',
   ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
   ADD_TASK_FAIL: 'ADD_TASK_FAIL',

   SET_TASK_EDITING: 'SET_TASK_EDITING'
}

export default taskTypes
