const types = {
   FETCH_TASK: 'FETCH_TASK',
   FETCH_TASK_SUCCESS: 'FETCH_TASK_SUCCESS',
   FETCH_TASK_FAIL: 'FETCH_TASK_FAIL',

   SEARCH_TASK: 'SEARCH_TASK',
   SEARCH_TASK_SUCCESS: 'SEARCH_TASK_SUCCESS'
}

export default types
